language: generic 
sudo: required
services: 
    - docker


before_install:
    # - docker build -t vision333/docker-react  -f dockerfile.dev .
    - docker build -t vision333/docker-react -f Dockerfile.dev .
script:
    # old way of doing things below: for testing
    # - docker run vision333/docker-react  npm run test -- --coverage

    # new way of doing things: for testing
    - docker run -e CI=true vision333/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-627766311941"
    bucket_path: "docker-react"
    on: 
        branch: master
        access_key_id: "$AWWS_ACCESS_KEY"
        secret_access_key:
            secure: "$AWS_SECRET_KEY"




    